package bqfontfix;

import net.minecraft.launchwrapper.IClassTransformer;
import org.objectweb.asm.*;

public class BQFontFixFontRendererTransformer implements IClassTransformer {

    private static final String TARGET = "net.minecraft.client.gui.FontRenderer";

        @Override
            public byte[] transform(String name, String transformedName, byte[] basicClass) {

                    if (basicClass == null || !name.equals(TARGET)) {
                                return basicClass;
                                        }

                                                System.out.println("[BQFontFix] Patching FontRenderer: " + name);

                                                        try {
                                                                    ClassReader cr = new ClassReader(basicClass);
                                                                                ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

                                                                                            ClassVisitor cv = new ClassVisitor(Opcodes.ASM5, cw) {
                                                                                                            @Override
                                                                                                                            public MethodVisitor visitMethod(int access, String methodName, String desc, String signature, String[] exceptions) {
                                                                                                                                                MethodVisitor mv = super.visitMethod(access, methodName, desc, signature, exceptions);
                                                                                                                                                                    return new MethodVisitor(Opcodes.ASM5, mv) {

                                                                                                                                                                                            @Override
                                                                                                                                                                                                                    public void visitCode() {
                                                                                                                                                                                                                                                super.visitCode();

                                                                                                                                                                                                                                                                            // inject before anything happens
                                                                                                                                                                                                                                                                                                        super.visitMethodInsn(
                                                                                                                                                                                                                                                                                                                                            Opcodes.INVOKESTATIC,
                                                                                                                                                                                                                                                                                                                                                                                "org/lwjgl/opengl/GL11",
                                                                                                                                                                                                                                                                                                                                                                                                                    "glTexParameteri",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "(III)V",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    super.visitLdcInsn(3553); // GL_TEXTURE_2D
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                super.visitLdcInsn(10241); // GL_TEXTURE_MIN_FILTER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            super.visitLdcInsn(9729);  // GL_LINEAR

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        super.visitMethodInsn(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Opcodes.INVOKESTATIC,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "org/lwjgl/opengl/GL11",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "glTexParameteri",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "(III)V",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    super.visitLdcInsn(3553); // GL_TEXTURE_2D
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                super.visitLdcInsn(10240); // GL_TEXTURE_MAG_FILTER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            super.visitLdcInsn(9729);  // GL_LINEAR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cr.accept(cv, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return cw.toByteArray();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (Exception e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("[BQFontFix] ERROR: " + e);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return basicClass;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        