package bqfontfix;

import net.minecraftforge.fml.common.FMLLog;
import net.minecraft.launchwrapper.IClassTransformer;
import org.objectweb.asm.*;

public class BQFontFixDiscoveryTransformer implements IClassTransformer {

    @Override
        public byte[] transform(String name, String transformedName, byte[] basicClass) {

                if (basicClass == null || name == null) return basicClass;

                        try {
                                    ClassReader cr = new ClassReader(basicClass);
                                                ClassWriter cw = new ClassWriter(0);

                                                            ClassVisitor cv = new ClassVisitor(Opcodes.ASM5, cw) {
                                                                            @Override
                                                                                            public MethodVisitor visitMethod(int access, String methodName, String desc,
                                                                                                                                             String signature, String[] exceptions) {

                                                                                                                                                                 MethodVisitor mv = super.visitMethod(access, methodName, desc, signature, exceptions);

                                                                                                                                                                                     return new MethodVisitor(Opcodes.ASM5, mv) {
                                                                                                                                                                                                             @Override
                                                                                                                                                                                                                                     public void visitMethodInsn(int opcode, String owner, String name2, String desc2, boolean itf) {

                                                                                                                                                                                                                                                                 // match GL11.glTexParameteri call
                                                                                                                                                                                                                                                                                             if (opcode == Opcodes.INVOKESTATIC &&
                                                                                                                                                                                                                                                                                                                             owner.equals("org/lwjgl/opengl/GL11") &&
                                                                                                                                                                                                                                                                                                                                                             name2.equals("glTexParameteri") &&
                                                                                                                                                                                                                                                                                                                                                                                             desc2.equals("(III)V")) {

                                                                                                                                                                                                                                                                                                                                                                                                                             FMLLog.log.info("[BQFontFix-DISCOVERY] FOUND in class: "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     + transformedName
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             + " method: " + methodName
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     super.visitMethodInsn(opcode, owner, name2, desc2, itf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         cr.accept(cv, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return cw.toByteArray();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (Throwable t) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return basicClass;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     