package bqfontfix;

import net.minecraft.launchwrapper.IClassTransformer;
import org.objectweb.asm.*;

public class BQFontFixTransformer implements IClassTransformer {

    private static final String TARGET_CLASS = "betterquesting/api2/utils/BqFontRenderer";

        @Override
            public byte[] transform(String name, String transformedName, byte[] basicClass) {
                    if (name == null) return basicClass;

                            if (!name.equals(TARGET_CLASS.replace('/', '.'))) {
                                        return basicClass;
                                                }

                                                        System.out.println("[BQFontFix] Patching class: " + name);

                                                                ClassReader cr = new ClassReader(basicClass);
                                                                        ClassWriter cw = new ClassWriter(cr, ClassWriter.COMPUTE_FRAMES);

                                                                                ClassVisitor cv = new ClassVisitor(Opcodes.ASM5, cw) {
                                                                                            @Override
                                                                                                        public MethodVisitor visitMethod(int access, String methodName, String desc, String signature, String[] exceptions) {

                                                                                                                        boolean isTargetMethod = false;

                                                                                                                                        // match: protected float func_78266_a(int, boolean)
                                                                                                                                                        if (methodName.equals("func_78266_a") && desc.equals("(IZ)F"))
                                                                                                                                                                            isTargetMethod = true;

                                                                                                                                                                                            // match: protected float func_78277_a(char, boolean)
                                                                                                                                                                                                            if (methodName.equals("func_78277_a") && desc.equals("(CZ)F"))
                                                                                                                                                                                                                                isTargetMethod = true;

                                                                                                                                                                                                                                                if (!isTargetMethod) {
                                                                                                                                                                                                                                                                    return super.visitMethod(access, methodName, desc, signature, exceptions);
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                    System.out.println("[BQFontFix] Patching method: " + methodName + desc);

                                                                                                                                                                                                                                                                                                                    MethodVisitor mv = super.visitMethod(access, methodName, desc, signature, exceptions);
                                                                                                                                                                                                                                                                                                                                    return new RemoveGLTexParamCalls(api, mv);
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                cr.accept(cv, ClassReader.SKIP_FRAMES);
                                                                                                                                                                                                                                                                                                                                                                        return cw.toByteArray();
                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                /** Removes calls to GL11.glTexParameteri */
                                                                                                                                                                                                                                                                                                                                                                                    private static class RemoveGLTexParamCalls extends MethodVisitor {

                                                                                                                                                                                                                                                                                                                                                                                            public RemoveGLTexParamCalls(int api, MethodVisitor mv) {
                                                                                                                                                                                                                                                                                                                                                                                                        super(api, mv);
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                public void visitMethodInsn(int opcode, String owner, String name, String desc, boolean itf) {

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Match GL11.glTexParameteri(int, int, int)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (opcode == Opcodes.INVOKESTATIC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            && owner.equals("org/lwjgl/opengl/GL11")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                && name.equals("glTexParameteri")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    && desc.equals("(III)V")) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("[BQFontFix]   Removed call: GL11.glTexParameteri");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Skip emitting this instruction (NOP)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            super.visitMethodInsn(opcode, owner, name, desc, itf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        