package bqfontfix;

import net.minecraft.launchwrapper.IClassTransformer;
import org.objectweb.asm.*;

public class BQPatchTextRenderer implements IClassTransformer {

    private static final String TARGET = "betterquesting/client/gui2/editors/blocks/PanelTextBox_GuiRectText";

        @Override
            public byte[] transform(String name, String transformedName, byte[] basicClass) {
                    if (name == null || basicClass == null) return basicClass;

                            if (!name.equals(TARGET)) return basicClass;

                                    try {
                                                ClassReader cr = new ClassReader(basicClass);
                                                            ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

                                                                        ClassVisitor cv = new ClassVisitor(Opcodes.ASM5, cw) {
                                                                                        @Override
                                                                                                        public MethodVisitor visitMethod(int access, String methodName, String desc,
                                                                                                                                                         String signature, String[] exceptions) {
                                                                                                                                                                             MethodVisitor mv = super.visitMethod(access, methodName, desc, signature, exceptions);
                                                                                                                                                                                                 return new StripTexParamCalls(Opcodes.ASM5, mv);
                                                                                                                                                                                                                 }
                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                         cr.accept(cv, ClassReader.SKIP_FRAMES);
                                                                                                                                                                                                                                                     return cw.toByteArray();

                                                                                                                                                                                                                                                             } catch (Exception e) {
                                                                                                                                                                                                                                                                         System.out.println("[BQFontFix] ERROR: " + e);
                                                                                                                                                                                                                                                                                     return basicClass;
                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                     private static class StripTexParamCalls extends MethodVisitor {

                                                                                                                                                                                                                                                                                                             public StripTexParamCalls(int api, MethodVisitor mv) {
                                                                                                                                                                                                                                                                                                                         super(api, mv);
                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                         @Override
                                                                                                                                                                                                                                                                                                                                                 public void visitMethodInsn(int opcode, String owner, String name,
                                                                                                                                                                                                                                                                                                                                                                                     String desc, boolean itf) {

                                                                                                                                                                                                                                                                                                                                                                                                 if (opcode == Opcodes.INVOKESTATIC &&
                                                                                                                                                                                                                                                                                                                                                                                                                 owner.equals("org/lwjgl/opengl/GL11") &&
                                                                                                                                                                                                                                                                                                                                                                                                                                 name.equals("glTexParameteri") &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                 desc.equals("(III)V")) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         super.visitMethodInsn(opcode, owner, name, desc, itf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     